apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-on-k8s-deployment
  labels:
    app: zomato-on-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato-on-k8s
  template:
    metadata:
      labels:
        app: zomato-on-k8s
    spec:
      containers:
      - name: zomato-kg-ecr
        image: 992382367971.dkr.ecr.us-west-1.amazonaws.com/zomato-kg-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
