# apiVersion: v1
# kind: Service
# metadata:
#   name: zomato-k8s-service
# spec:
#   type: LoadBalancer 
#   selector:
#     app: zomato-on-k8s
#   ports:
#     - protocol: 'TCP'
#       port: 3000  
#       targetPort: 3000
     
apiVersion: v1
kind: Service
metadata:
  name: zomato-k8s-service
  namespace: zomato
spec:
  selector:
    app: zomato-k8s-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
