name: zomato

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    
    - name: build the docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push the docker image to docker hub
      uses: docker/build-push-action@v4
      with:
         context: .
         dockerfile: Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}
